# Postgresql database for production, development and testing.
#
development:
  adapter: postgresql
  encoding: unicode
  database: knowledgethief_development
  pool: 5
  timeout: 5000
  username: ben
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: knowledgethief_test
  pool: 5
  timeout: 5000
  username: ben
  password: