require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PathsController do

  # This should return the minimal set of attributes required to create a valid
  # Path. As you add validations to Path, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PathsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all paths as @paths" do
      path = Path.create! valid_attributes
      get :index, {}, valid_session
      assigns(:paths).should eq([path])
    end
  end

  describe "GET show" do
    it "assigns the requested path as @path" do
      path = Path.create! valid_attributes
      get :show, {:id => path.to_param}, valid_session
      assigns(:path).should eq(path)
    end
  end

  describe "GET new" do
    it "assigns a new path as @path" do
      get :new, {}, valid_session
      assigns(:path).should be_a_new(Path)
    end
  end

  describe "GET edit" do
    it "assigns the requested path as @path" do
      path = Path.create! valid_attributes
      get :edit, {:id => path.to_param}, valid_session
      assigns(:path).should eq(path)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Path" do
        expect {
          post :create, {:path => valid_attributes}, valid_session
        }.to change(Path, :count).by(1)
      end

      it "assigns a newly created path as @path" do
        post :create, {:path => valid_attributes}, valid_session
        assigns(:path).should be_a(Path)
        assigns(:path).should be_persisted
      end

      it "redirects to the created path" do
        post :create, {:path => valid_attributes}, valid_session
        response.should redirect_to(Path.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved path as @path" do
        # Trigger the behavior that occurs when invalid params are submitted
        Path.any_instance.stub(:save).and_return(false)
        post :create, {:path => { "name" => "invalid value" }}, valid_session
        assigns(:path).should be_a_new(Path)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Path.any_instance.stub(:save).and_return(false)
        post :create, {:path => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested path" do
        path = Path.create! valid_attributes
        # Assuming there are no other paths in the database, this
        # specifies that the Path created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Path.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => path.to_param, :path => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested path as @path" do
        path = Path.create! valid_attributes
        put :update, {:id => path.to_param, :path => valid_attributes}, valid_session
        assigns(:path).should eq(path)
      end

      it "redirects to the path" do
        path = Path.create! valid_attributes
        put :update, {:id => path.to_param, :path => valid_attributes}, valid_session
        response.should redirect_to(path)
      end
    end

    describe "with invalid params" do
      it "assigns the path as @path" do
        path = Path.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Path.any_instance.stub(:save).and_return(false)
        put :update, {:id => path.to_param, :path => { "name" => "invalid value" }}, valid_session
        assigns(:path).should eq(path)
      end

      it "re-renders the 'edit' template" do
        path = Path.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Path.any_instance.stub(:save).and_return(false)
        put :update, {:id => path.to_param, :path => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested path" do
      path = Path.create! valid_attributes
      expect {
        delete :destroy, {:id => path.to_param}, valid_session
      }.to change(Path, :count).by(-1)
    end

    it "redirects to the paths list" do
      path = Path.create! valid_attributes
      delete :destroy, {:id => path.to_param}, valid_session
      response.should redirect_to(paths_url)
    end
  end

end
